version: "2"
services:
    app:
        container_name: app
        restart: always
        build: ./server
        ports: 
            - "8000:8000"
        links:
            - mongo
            - redis
    mongo:
        container_name: mongo
        image: mongo
        hostname: mongo
        restart: always
        expose:
            - "27017"
        volumes: 
            - ./data:/data/db
        ports:
            - "27017:27017"
    redis:
        image: "redis:latest"

    client:
        container_name: client
        restart: always
        build: ./client
        ports: 
            - "9000:9000"
        links:
            - app